# Generated by Django 5.2.6 on 2025-10-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('make', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField(blank=True, max_length=5)),
                ('wheels', models.CharField(blank=True, max_length=100)),
                ('mods', models.TextField()),
            ],
        ),
    ]
