# Generated by Django 5.2.7 on 2026-01-19 21:26

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_options_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
