# Generated by Django 5.2.6 on 2025-10-23 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1885), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
