# Generated by Django 5.2.7 on 2026-01-26 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userrelationships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userrelationships',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to'), name='unique_rel'),
        ),
    ]
