# Generated by Django 5.2.6 on 2025-10-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='wheels',
        ),
    ]
