# Generated by Django 5.2.6 on 2025-10-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_car_wheels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id_car',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mods',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_make_model', models.CharField(blank=True, max_length=20)),
                ('wheel_model', models.CharField(blank=True, max_length=40)),
                ('tire_make_model', models.CharField(blank=True, max_length=100)),
                ('suspension_make_model', models.CharField(blank=True, max_length=100)),
                ('suspension_type', models.CharField(blank=True, max_length=40)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.car')),
            ],
        ),
    ]
