# Generated by Django 5.2.6 on 2025-10-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_car_id_car_remove_car_user_car_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='car',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Setup',
        ),
    ]
