# Generated by Django 5.2.6 on 2025-10-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_setup_car_delete_car_delete_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/default-profile-pic.png', upload_to='profile_images/'),
        ),
    ]
