# Generated by Django 5.2.6 on 2025-10-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-profile-pic.jpeg', upload_to='profile_images/'),
        ),
    ]
